all: esercizio5 esercizio6 mcd

esercizio5: Esercizio5.cpp
        g++ -o build/Esercizio5 Esercizio5.cpp

esercizio6: Esercizio6.cpp
        g++ -o build/Esercizio6 Esercizio6.cpp

mcd: MCDEs.cpp
        g++ -o build/MCD MCDEs.cpp

clean:
        rm -f build/*
