all: esercizio1 esercizio7 esercizio8 esercizio9

esercizio1: Esercizio1.cpp
	g++ -o build/Es1  Esercizio1.cpp

esercizio7: Esercizio7.cpp
	g++ -o build/Es7 Esercizio7.cpp

esercizio8: Esercizio8.cpp
	g++ -o build/Es8 Esercizio8.cpp

esercizio9: Esercizio9.cpp
	g++ -o build/Es9 Esercizio9.cpp

clean:
	rm -f build/*

