all: register checknumber ConvertBinaryToDec IndovinaNumeroCPUvsCPU PrestitoCasa Quadrati QuadratoTico RettangoloAndTriangolo negozianterandom indovinanumero

register: Register.cpp
	g++ -o build/register Register.cpp

clean:
	rm -f build/*

checknumber: CheckNumber.cpp
	g++ -o build/checknumber CheckNumber.cpp

ConvertBinaryToDec: ConvertBinaryToDec.cpp
	g++ -o build/ConvertBinaryToDec ConvertBinaryToDec.cpp

IndovinaNumeroCPUvsCPU: IndovinaNumeroCPUvsCPU.cpp
	g++ -o build/IndovinaNumeroCPUvsCPU IndovinaNumeroCPUvsCPU.cpp

PrestitoCasa: PrestitoCasa.cpp
	g++ -o build/PrestitoCasa PrestitoCasa.cpp

Quadrati: Quadrati.cpp
	g++ -o build/Quadrati Quadrati.cpp

QuadratoTico: QuadratoTico.cpp
	g++ -o build/QuadratoTico QuadratoTico.cpp

RettangoloAndTriangolo: RettangoloAndTriangolo.cpp
	g++ -o build/RettangoloAndTriangolo RettangoloAndTriangolo.cpp

negozianterandom: NegozianteRandom.cpp
	g++ -o build/negozianterandom NegozianteRandom.cpp

negozianterandom: PrestitoCasa.cpp
	g++ -o build/PrestitoCasa PrestitoCasa.cpp

indovinanumero: IndovinaNumero.cpp
	g++ -o build/indovinanumero IndovinaNumero.cpp