all: esercizio3 esercizio5 esercizio6 esercizio7 esercizio10

esercizio3: Esercizio3.cpp 
	g++ -o build/Es3  Esercizio3.cpp

esercizio5: Esercizio5.cpp
	g++ -o build/Es5  Esercizio5.cpp

esercizio6: Esercizio6.cpp
	g++ -o build/Es6  Esercizio6.cpp

esercizio7: Esercizio7.cpp
	g++ -o build/Es7 Esercizio7.cpp

esercizio10: Esercizio10.cpp
	g++ -o build/Es10 Esercizio10.cpp